spring:
    datasource:
        continue-on-error: true
        initialization-mode: always
        password: NWzuxwb8UBCovoXNEcom
        url: jdbc:postgresql://swapbook-database.cwc8pgvekl9i.eu-central-1.rds.amazonaws.com:5432/postgres
        username: postgres
    jpa:
        hibernate:
            ddl-auto: none
            show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    mail:
        host: smtp.gmail.com
        username: swapbook.noreply@gmail.com
        password: el#w)na7
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

