spring:
    datasource:
        continue-on-error: true
        initialization-mode: always
        password: bvget1OwM8lw3cNv0XqCV1XURFbOY2lF
        url: jdbc:postgresql://dumbo.db.elephantsql.com:5432/dphhzeup
        username: dphhzeup
    jpa:
        hibernate:
            ddl-auto: none
            show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    mail:
        host: smtp.gmail.com
        username: swapbook.noreply@gmail.com
        password: el#w)na7
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

